[package]
name = "dash-mpd-cli"
version = "0.1.6"
authors = ["Eric Marsden <eric.marsden@risk-engineering.org>"]
license = "MIT"
description = "Download content from a DASH-MPEG or DASH-WebM MPD manifest"
readme = "README.md"
repository = "https://github.com/emarsden/dash-mpd-cli"
keywords = ["video", "streaming", "DASH", "MPEG", "download"]
categories = ["command-line-utilities", "multimedia", "multimedia::video"]
edition = "2021"
publish = true


[dependencies]
dash-mpd = ">=0.6.2"
reqwest = { version = "0.11", default-features = false, features = ["blocking", "gzip", "brotli", "rustls-tls", "socks"] }
colored = "2"
indicatif = "0.17"
clap = { version = "4", features = ["cargo", "unicode"] }
anyhow = "1"
log = "0.4"
env_logger = "0.10"

[profile.release]
opt-level = "z"  # optimize for size
lto = "fat"
